a = input('Digite algo:')
print('O tipo primitivo desse valor é:',type(a))
print('Só tem espaços?',a.isspace())
print('é um numero?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('é alfanumerico?',a.isalnum())
print('Esta em maisculas?',a.isupper())
print('Esta em minúsculas',a.islower())
