nome = str(input('Digite o nome do Aluno:'))
n1 = float(input('Digite a nota 1:'))
n2 = float(input('Digite a nota 2:'))
n3 = float(input('Digite a nota 3:'))
n4 = float(input('Digite a nota 4:'))
print('A media do aluno {} foi {:.1f}'.format(nome,(n1+n2+n3+n4)/4))