import cores
p = f'Este é um texto de teste'.center(50)
print(cores.corVermelha(p))
print(cores.corVerde(p))
print(cores.corAmarela(p))
print(cores.corAzul(p))
print(cores.corRoxa(p))
print(cores.corEsmeralda(p))
print(cores.fundoVermelho(p))
print(cores.fundoVerde(p))
print(cores.fundoAmarelo(p))
print(cores.fundoAzul(p))
print(cores.fundoRoxo(p))
print(cores.fundoEsmeralda(p))
